site_name: BioPro Synthetic Biology Documentation
site_url: https://KalaimaranB.github.io/BioPro-SyntheticBiology
site_description: Documentation for the BioPro Synthetic Biology plugin.
site_author: Kalaimaran Balasothy

repo_name: BioPro Synthetic Biology
repo_url: https://github.com/KalaimaranB/BioPro-SyntheticBiology

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

nav:
  - "Welcome": index.md
